# Generated by Django 2.2.6 on 2019-12-04 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RedNeuronalResultados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clasificacion', models.TextField()),
                ('periodo', models.TextField(choices=[('DIAS', 'DIAS'), ('SEMANAS', 'SEMANAS'), ('MESES', 'MESES')])),
                ('look_back', models.IntegerField()),
                ('neuronas', models.IntegerField()),
                ('epocas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RegistroVenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('empresa', models.TextField()),
                ('ruc', models.TextField()),
                ('precio', models.FloatField()),
                ('tipo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DatosRedNeuronalTrain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dam', models.IntegerField(blank=True, null=True)),
                ('pema', models.IntegerField(blank=True, null=True)),
                ('rmse', models.IntegerField(blank=True, null=True)),
                ('precio', models.IntegerField(blank=True, null=True)),
                ('real', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateField()),
                ('entrenamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='getResultadosServiciosTrain', to='prediccion.RedNeuronalResultados')),
            ],
        ),
        migrations.CreateModel(
            name='DatosRedNeuronalTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.IntegerField(blank=True, null=True)),
                ('future', models.DateField()),
                ('entrenamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='getResultadosServiciosTest', to='prediccion.RedNeuronalResultados')),
            ],
        ),
    ]
